---
- set_fact:
    greeting_application_file: "/opt/engineering/greeting.py"

- name:
  template:
    src: "../templates/developers.j2"
    dest: "/etc/sudoers.d/developers"
    validate: visudo -cf '%s'
    group: root
    owner: root
    mode: 0440
    
